Wipes destination manifests on write. Resolves Issue #16
cake-contrib/Cake.AndroidAppManifest pull request #17
Opened 2017-11-27 15:36 UTC by lprichar

2017-11-27 16:06 UTC, jzeferino commented
@lprichar I've changed the base of the merge.
We also use develop as our main develop branch so your feature should derive from develop.
I will need to create the contributing guide for this from now on.

2017-11-27 22:09 UTC, jzeferino commented on src/Cake.AndroidAppManifest/AndroidAppManifest.cs
> +            using (var stream = File.Open(fileName, FileMode.Create))
@lprichar Can you change the `File.Open(string path, System.IO.FileMode mode)` to `File.Open(string path, System.IO.FileMode mode, System.IO.FileAccess access)` so we can specify `FileAccess` as `ReadWrite `? 
See documentation [here](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileaccess?view=netframework-4.7.1) fore more detail.

2017-11-27 22:10 UTC, jzeferino requested changes
Please review my comment, and let me know what you think.

2017-11-28 02:41 UTC, lprichar commented
You might consider changing your default branch to develop if you'd like PR's to go against there.  Also, I'm pretty sure ReadWrite is the default for all mode's other than Append, but I implemented as requested, no harm in being explicit I guess.

2017-11-29 00:16 UTC, jzeferino commented
I don't wan't to change the default branch to master since the master represents the current release and it contains the readme for it.

development can/should have more new features/updates that we don't want to show in the main github page.

We're using gitflow for branch management but it isn't clear yet. I will create a contributing guide with it.

The requested change was for clarity only.

2017-11-29 00:17 UTC, merged